name: Build

on: push

jobs:
  build:
    name: 'Kotlin=${{ matrix.kotlin }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kotlin: [ 1.6.21, 1.7.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Assemble
        run: ./gradlew assembleDebug -PkotlinVersion=${{ matrix.kotlin }}
